maa-dataops-example-ops:
  LIBRARY: epf
  TERRAFORM_VERSION: 1.4.7
  TERRAGRUNT_VERSION: 0.50.14
  SOLUTION_REPO: maa-dataops-example-solutions
  DAG_ID: blueprint_ddl_liquibase_v2
  ACCOUNT_ROLE_NAME: Enterprise/MAAGATEKEEPERJENKINS
  CLOUD_NAME: evernorth-qp-gov-solns-openshift-devops1
  EKS_GATEKEEPER_CLOUD_NAME: evernorth-qp-gov-solns-eks-prod
  CONTAINER_IMAGE: registry.cigna.com/enterprise-devops/aws-d-megatainer
  CONTAINER_VERSION: 1.0.14-2
  CONTAINER_CPU: 1000
  CONTAINER_MEMORY: 4000
  CHECKMARX_ENABLED: 0
  CHECKMARX_DEBUG: 1
  CHECKMARX_CREDENTIALS: checkmarx_credentials
  CHECKMARX_PROJECT_TEAM_NAME: MEDICARE_ADVANTAGE_ANALYTICS
  CHECKMARX_NAME: maa-dataops-example-solutions
  CHECKMARX_EXCLUDE_FOLDERS: plz-out, commands, test_resources, third_party, aws_glue_libs, tests
  SONAR_ENABLED: 0
  SONAR_CREDENTIALS: sonarqube-service-id
  SONAR_KEY: sonar.projectKey=maa-dataops-example-solutions
  SONAR_NAME: sonar.projectName=maa-dataops-example-solutions
  SONAR_BASE_DIR: sonar.projectBaseDir=module/aws/
  SONAR_SOURCES: sonar.sources=python_code/src
  SONAR_TESTS: sonar.tests=python_code/tests
  SONAR_REPORTS: sonar.python.coverage.reportPaths=python_code/reports
  SECURITY_REVIEW_ID: RITM7392745
  TDV_SERVICE_ACCOUNT_NAME_DEV: SVT_DATAOPS_DEV
  TDV_SERVICE_ACCOUNT_NAME_DEV2: SVT_DATAOPS_DEV
  TDV_SERVICE_ACCOUNT_NAME_INT: SVT_DATAOPS_INT
  TDV_SERVICE_ACCOUNT_NAME_UAT: SVT_DATAOPS_UAT
  TDV_SERVICE_ACCOUNT_NAME_ITE: SVT_DATAOPS_UAT
  TDV_SERVICE_ACCOUNT_NAME_QA: SVT_DATAOPS_UAT
  TDV_SERVICE_ACCOUNT_NAME_PRD: SVT_DATAOPS_PRD

