filegroup(
    name = "terraform",
    srcs = glob([
        "**/*.tf",
        "**/*.hcl",
        "*.hcl",
        "**/*.tfvars",
        "**/*.sh",
        "**/*.yaml",
        "*.yaml",
        "**/*.yml",
        "*.yml",
        "**/*.py"
    ]),
    visibility = ["PUBLIC"],
)