name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      git_branch:
        description: 'Select a git branch'
        required: true
        default: 'main'
      # tdv_environment:
      #   description: 'Select a TDV environment'
      #   required: true
      #   default: 'dev'

jobs:
  fetch_branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get_branches.outputs.branches }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch Git Branches
      id: get_branches
      run: |
        GIT_BRANCHES=$(git branch -r | grep -v '\->' | sed 's/origin\///' | tr '\n' ' ')
        echo "::set-output name=branches::$GIT_BRANCHES"

  build:
    runs-on: ubuntu-latest
    needs: fetch_branches
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.git_branch }}

    - name: Set Environment Variables
      run: |
        case "${{ github.event.inputs.git_branch }}" in
          dev)
            echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
            ;;
          test)
            echo "ACCOUNT_NUMBER=883528617975" >> $GITHUB_ENV
            echo "ENV=test" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            ;;
          main)
            echo "ACCOUNT_NUMBER=160989692528" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_PRD" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=" >> $GITHUB_ENV
            ;;
          *)
            echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
            ;;
        esac

    - name: Print Environment Variables
      run: |
        echo "SOLUTION_BRANCH: ${{ github.event.inputs.git_branch }}"
        echo "TDV_ENV: ${{ github.event.inputs.tdv_environment }}"
        echo "ACCOUNT_NUMBER: ${{ env.ACCOUNT_NUMBER }}"
        echo "ENV: ${{ env.ENV }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_1: ${{ env.TDV_SERVICE_ACCOUNT_NAME_1 }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_2: ${{ env.TDV_SERVICE_ACCOUNT_NAME_2 }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_3: ${{ env.TDV_SERVICE_ACCOUNT_NAME_3 }}"
