name: CI Pipeline - Step 1

on:
  workflow_dispatch:
    inputs:
      git_branch:
        description: 'Select a git branch'
        required: true
        type: choice
        options: 
          - dev
          - test
          - main

jobs:
  select_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Get Branch Name from Workflow Trigger
      id: get_branch
      run: |
        # Get the current branch name where the workflow is triggered
        BRANCH="${{ github.ref_name }}"
        echo "Branch identified: $BRANCH"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        
    - name: Set TDV Environment Choices
      id: set_tdv_env_choices
      run: |
        ENV_DEV="dev dev2"
        ENV_TEST="int uat qa"
        ENV_PROD="prd"

        case "${{ github.event.inputs.git_branch }}" in
          dev)
            TDV_ENV_CHOICES="$ENV_DEV"
            ;;
          test)
            TDV_ENV_CHOICES="$ENV_TEST"
            ;;
          main)
            TDV_ENV_CHOICES="$ENV_PROD"
            ;;
        esac

        echo "TDV_ENV_CHOICES=$TDV_ENV_CHOICES" >> $GITHUB_ENV
        echo "::set-output name=tdv_env_choices::$TDV_ENV_CHOICES"

    - name: Output Available TDV Environments
      run: |
        echo "Available TDV Environments for branch ${{ github.event.inputs.git_branch }}: ${{ steps.set_tdv_env_choices.outputs.tdv_env_choices }}"
      
    - name: Create an Issue if None Exists
      id: create_issue
      uses: peter-evans/create-issue@v2
      with:
        title: "TDV Environment Selection Required"
        body: |
          For branch `${{ env.BRANCH }}`, the available TDV environments are:
          `${{ steps.set_tdv_env_choices.outputs.tdv_env_choices }}`
          Please comment on this issue with the TDV environment you want to select.
          Example: `/select tdv dev`

    - name: Create or Update Issue Comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ steps.create_issue.outputs.issue-number }}
        body: |
          ## TDV Environment Selection Required
          - For branch `${{ env.BRANCH }}`, the available TDV environments are:
            `${{ steps.set_tdv_env_choices.outputs.tdv_env_choices }}`
          - Please comment on this issue with the TDV environment you want to select. For example:
            `/select tdv dev`
