name: CI Pipeline - Step 1

permissions:
  issues: write

on:
  workflow_dispatch:
    inputs:
      git_branch:
        description: 'Select a git branch'
        required: true
        type: choice
        options: 
          - dev
          - test
          - main
          - default

jobs:
  select_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Get Branch Name from Workflow Trigger
      id: get_branch
      run: |
        # Get the current branch name where the workflow is triggered
        BRANCH="${{ github.ref_name }}"
        echo "Branch identified: $BRANCH"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        
    - name: Set TDV Environment Choices
      id: set_tdv_env_choices
      run: |
        ENV_DEV="dev dev2"
        ENV_TEST="int uat qa"
        ENV_PROD="prd"
        ENV_ALL="$ENV_DEV $ENV_TEST $ENV_PROD"

        case "${{ github.event.inputs.git_branch }}" in
          dev)
            TDV_ENV_CHOICES="$ENV_DEV"
            ;;
          test)
            TDV_ENV_CHOICES="$ENV_TEST"
            ;;
          main)
            TDV_ENV_CHOICES="$ENV_PROD"
            ;;
          *)
            TDV_ENV_CHOICES="$ENV_ALL"
            ;;
        esac

        echo "TDV_ENV_CHOICES=$TDV_ENV_CHOICES" >> $GITHUB_ENV
        echo "::set-output name=tdv_env_choices::$TDV_ENV_CHOICES"
        echo "::set-secret name=SELECTED_BRANCH::${{ github.event.inputs.branch_name }}"

    - name: Output Available TDV Environments
      run: |
        echo "Available TDV Environments for branch ${{ github.event.inputs.git_branch }}: ${{ steps.set_tdv_env_choices.outputs.tdv_env_choices }}"
      
    - name: Create GitHub Issue
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const branch = "${{ github.event.inputs.git_branch }}";
          const tdvEnvChoices = "${{ github.event.inputs.tdv_env_choices }}";
          const issueTitle = "TDV Environment Selection Required";
          const issueBody = `
          ## TDV Environment Selection Required
          - For branch \`${branch}\`, the available TDV environments are:
          \`${tdvEnvChoices}\`
          - Please comment on this issue with the TDV environment you want to select. For example:
          \`/select tdv dev\`
          `;

          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody,
          });

          console.log(`Created issue: ${issue.data.html_url}`);
