name: CI Pipeline - Step 3

on:
  workflow_dispatch
  # workflow_run:
  #   workflows: 
  #     - "CI Pipeline - Step 1"
  #     - "CI Pipeline - Step 2"
  #   types:
  #     - completed
  

jobs:
  get-run-id:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest run_id of another workflow
        id: get_run_id
        run: |
          workflow_name="step1.yml"  # Name of the workflow
          repo_owner="${{ github.repository_owner }}"
          repo_name="${{ github.repository }}"
  
          # Call the GitHub API to list workflow runs by workflow name
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/{$repo_owner}/$repo_name/actions/workflows)

          echo "$response"
  
          # Extract the run_id of the latest workflow run
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
  
          echo "Latest run_id is: $run_id"
          echo "::set-output name=run_id::$run_id"
  
      - name: Use the run_id
        run: |
          echo "The run_id of the latest workflow is: ${{ steps.get_run_id.outputs.run_id }}"


  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download github_branch
        uses: actions/download-artifact@v3
        with:
          name: github_branch
  
      - name: Download tdv_env
        uses: actions/download-artifact@v3
        with:
          name: tdv_env
  
      - name: Verify artifacts
        run: |
          cat artifact1.txt
          cat artifact2.txt
