name: CI Pipeline - Step 3

on:
  workflow_dispatch
  # workflow_run:
  #   workflows: 
  #     - "CI Pipeline - Step 2"
  #   types:
  #     - completed
  

jobs:
  get-git-branch-value:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Get the latest run_id of Step 1 workflow
        id: get_run_id_step_1
        run: |
          workflow_name="step1.yml"  # Name of the workflow
          repo_name="${{ github.repository }}"
          api_url="https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows"
          echo "API URL: $api_url"
  
          # Call the GitHub API to list workflow runs by workflow name
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_name/actions/workflows/$workflow_name/runs?per_page=1)
  
          # Extract the run_id of the latest workflow run
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
  
          echo "Latest run_id is: $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
  
      - name: Use the run_id
        run: |
          echo "The run_id of the latest workflow is: ${{ steps.get_run_id_step_1.outputs.run_id }}"

      - name: Download github_branch
        uses: actions/download-artifact@v4
        with:
          name: github_branch
          github-token : ${{ secrets.GIT_TOKEN}}
          repository : ${{ github.repository }}
          run-id : ${{ steps.get_run_id_step_1.outputs.run_id }}
          
      - name: Store artifacts Value
        id: get_branch
        run: |
           branch_value=$(cat github_branch)
           echo "branch_value=${branch_value}"
           echo "branch=${branch_value}" >> $GITHUB_OUTPUT
           echo $branch
      
  get-tdv-env-value:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.tdv_env.outputs.tdv_env }}
    steps:
      - name: Get the latest run_id of Step 2 workflow
        id: get_run_id_step_2
        run: |
          workflow_name="step2.yml"  # Name of the workflow
          repo_name="${{ github.repository }}"
          api_url="https://api.github.com/repos/$repo_owner/$repo_name/actions/workflows"
          echo "API URL: $api_url"
  
          # Call the GitHub API to list workflow runs by workflow name
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_name/actions/workflows/$workflow_name/runs?per_page=1)
  
          # Extract the run_id of the latest workflow run
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
  
          echo "Latest run_id is: $run_id"
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
  
      - name: Use the run_id
        run: |
          echo "The run_id of the latest workflow is: ${{ steps.get_run_id_step_2.outputs.run_id }}"

      - name: Download tdv_env
        uses: actions/download-artifact@v4
        with:
          name: tdv_env
          github-token : ${{ secrets.GIT_TOKEN}}
          repository : ${{ github.repository }}
          run-id : ${{ steps.get_run_id_step_2.outputs.run_id }}
          
      - name: Store artifacts Value
        id: tdv_env
        run: |
           tdv_env_value=$(cat tdv_env)
           echo "tdv_env_value=${tdv_env_value}"
           echo "tdv_env=${tdv_env_value}" >> $GITHUB_OUTPUT

  set-print-env-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Environnment variables
        id: set_env_variables
        run: |
          case "${{ needs.get-git-branch-value.outputs.branch-name }}" in
            dev)
              echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
              echo "ENV=dev" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
              ;;
            test)
              echo "ACCOUNT_NUMBER=883528617975" >> $GITHUB_ENV
              echo "ENV=test" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_UAT" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_UAT" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_UAT" >> $GITHUB_ENV
              ;;
            main)
              echo "ACCOUNT_NUMBER=160989692528" >> $GITHUB_ENV
              echo "ENV=prod" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_PRD" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_2=" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_3=" >> $GITHUB_ENV
              ;;
            *)
              echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
              echo "ENV=dev" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
              echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
              ;;
          esac

      - name: Print Environment Variables
        run: |
          echo "SOLUTION_BRANCH: ${{ needs.get-git-branch-value.outputs.branch-name }}"
          echo "TDV_ENV: ${{ needs.get-tdv-env-value.outputs.tdv_env }} "
          echo "ACCOUNT_NUMBER: ${{ env.ACCOUNT_NUMBER }}"
          echo "ENV: ${{ env.ENV }}"
          echo "TDV_SERVICE_ACCOUNT_NAME_1: ${{ env.TDV_SERVICE_ACCOUNT_NAME_1 }}"
          echo "TDV_SERVICE_ACCOUNT_NAME_2: ${{ env.TDV_SERVICE_ACCOUNT_NAME_2 }}"
          echo "TDV_SERVICE_ACCOUNT_NAME_3: ${{ env.TDV_SERVICE_ACCOUNT_NAME_3 }}"
