name: CI Pipeline - Step 2

on:
  issue_comment:
    types: [created]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check if Comment Contains TDV Selection
      id: check_comment
      run: |
        comment_body="${{ github.event.comment.body }}"
        echo "Comment body: $comment_body"
        if [[ "$comment_body" == /select*tdv* ]]; then
          tdv_env=$(echo "$comment_body" | sed 's/\/select tdv //')
          echo "TDV_ENV=$tdv_env" >> $GITHUB_ENV
        else
          echo "Not a valid TDV selection comment."
          exit 1
        fi
    

    - name: Print Selected TDV Environment
      if: steps.check_comment.outcome == 'success'
      run: |
        echo "Selected TDV Environment: ${{ env.TDV_ENV }}"

    - name: Set Environment Variables
      run: |
        case "${{ github.event.inputs.git_branch }}" in
          dev)
            echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
            ;;
          test)
            echo "ACCOUNT_NUMBER=883528617975" >> $GITHUB_ENV
            echo "ENV=test" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_UAT" >> $GITHUB_ENV
            ;;
          main)
            echo "ACCOUNT_NUMBER=160989692528" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_PRD" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=" >> $GITHUB_ENV
            ;;
          *)
            echo "ACCOUNT_NUMBER=215132885729" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_1=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_2=SVT_DATAOPS_DEV" >> $GITHUB_ENV
            echo "TDV_SERVICE_ACCOUNT_NAME_3=SVT_DATAOPS_INT" >> $GITHUB_ENV
            ;;
        esac

    - name: Print Environment Variables
      run: |
        echo "SOLUTION_BRANCH: ${{ github.event.inputs.git_branch }}"
        echo "TDV_ENV: ${{ env.TDV_ENV }} "
        echo "ACCOUNT_NUMBER: ${{ env.ACCOUNT_NUMBER }}"
        echo "ENV: ${{ env.ENV }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_1: ${{ env.TDV_SERVICE_ACCOUNT_NAME_1 }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_2: ${{ env.TDV_SERVICE_ACCOUNT_NAME_2 }}"
        echo "TDV_SERVICE_ACCOUNT_NAME_3: ${{ env.TDV_SERVICE_ACCOUNT_NAME_3 }}"
